# -*- coding: utf-8 -*-
"""bitcoin_automl_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Gxam7XMhLXoykY7LAIl5FmMAf3WtsWg

# AutoML Studio — Bitcoin + Image Processing + Tableau
> **Pipeline:** EDA → Cleaning → Augmentation → Preprocessing → Technical Indicators  
> → AutoML → **Image Processing** → **CNN Chart Pattern Classifier** → Tableau Export  

> **Dataset:** Bitcoin OHLCV · 2,953 rows · Apr 2013 – May 2021  
> **Image task:** CNN chart pattern recognition (Bull flag, H&S, Double top, Triangle, Cup & handle)  

---

## 0. Install & import
"""

import subprocess, sys
pkgs = ['pandas','numpy','matplotlib','seaborn','scikit-learn',
        'xgboost','lightgbm','opencv-python','Pillow','torch',
        'torchvision','imbalanced-learn','reportlab']
subprocess.check_call([sys.executable,'-m','pip','install','--quiet'] + pkgs)
print('All packages installed.')

import warnings; warnings.filterwarnings('ignore')
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import matplotlib.patches as patches
import seaborn as sns, cv2, os, json, io, datetime
from PIL import Image, ImageFilter, ImageEnhance, ImageOps
from pathlib import Path

from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import TimeSeriesSplit, cross_val_score
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report
from sklearn.feature_selection import SelectKBest, f_regression
from xgboost import XGBRegressor, XGBClassifier
import lightgbm as lgb

import torch, torch.nn as nn, torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import torchvision.models as models

plt.style.use('seaborn-v0_8-whitegrid')
BLUE='#185FA5'; GREEN='#3B6D11'; AMBER='#854F0B'; RED='#A32D2D'
PURPLE='#534AB7'; PURPLE_L='#EEEDFE'; TAB_ORANGE='#E97627'
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
np.random.seed(42); torch.manual_seed(42)
print(f'Device: {DEVICE}')
print('All imports OK.')

"""## 1. Load Bitcoin dataset"""

df = pd.read_csv('/content/Bitcoin.csv')
df.columns = ['Date','Open','High','Low','Close','Volume','Market_Cap']
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
df = df.sort_values('Date').reset_index(drop=True)
print(f'Shape: {df.shape}  |  {df["Date"].min().date()} → {df["Date"].max().date()}')
df.head()

"""## 2. EDA"""

fig, axes = plt.subplots(2, 2, figsize=(14, 7))
axes[0,0].plot(df['Date'], df['Close'], color=BLUE, lw=0.8)
axes[0,0].fill_between(df['Date'], df['Close'], alpha=0.08, color=BLUE)
axes[0,0].set_title('Bitcoin close price', fontweight='bold')
axes[0,0].yaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'${x:,.0f}'))

axes[0,1].bar(df['Date'], df['Volume']/1e9, color=BLUE, alpha=0.5, width=1)
axes[0,1].set_title('Volume ($B)', fontweight='bold')

df['Daily_Return'] = df['Close'].pct_change() * 100
rets = df['Daily_Return'].dropna()
n, bins, patches = axes[1,0].hist(rets, bins=80, edgecolor='none', alpha=0.75)
for b, p in zip(bins[:-1], patches):
    if b >= 0:
        p.set_facecolor(BLUE)
    else:
        p.set_facecolor(RED)
axes[1,0].axvline(0, color='black', lw=1)
axes[1,0].set_title('Daily returns distribution', fontweight='bold')

axes[1,1].plot(df['Date'], df['Market_Cap']/1e9, color=GREEN, lw=0.8)
axes[1,1].fill_between(df['Date'], df['Market_Cap']/1e9, alpha=0.08, color=GREEN)
axes[1,1].set_title('Market cap ($B)', fontweight='bold')

for ax in axes.flat: ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('/tmp/btc_eda.png', dpi=130, bbox_inches='tight')
plt.show()

"""## 3. Technical indicators"""

def sma(s, p): return s.rolling(p).mean()
def ema(s, p): return s.ewm(span=p, adjust=False).mean()
def rsi(s, p=14):
    d=s.diff(); g=d.clip(lower=0).rolling(p).mean(); l=(-d.clip(upper=0)).rolling(p).mean()
    return 100-(100/(1+g/l))
def macd(s, f=12, sl=26, sig=9):
    m=ema(s,f)-ema(s,sl); return m, ema(m,sig)
def bollinger(s, p=20):
    sm=sma(s,p); std=s.rolling(p).std()
    return sm+2*std, sm-2*std, (4*std)/sm

df['SMA_20'] = sma(df['Close'],20)
df['SMA_50'] = sma(df['Close'],50)
df['EMA_20'] = ema(df['Close'],20)
df['RSI_14'] = rsi(df['Close'],14)
df['MACD'], df['MACD_Signal'] = macd(df['Close'])
df['BB_Upper'], df['BB_Lower'], df['BB_Width'] = bollinger(df['Close'])

recent = df.tail(365)
fig, axes = plt.subplots(3,1,figsize=(14,10),gridspec_kw={'height_ratios':[3,1,1]})
axes[0].plot(recent['Date'],recent['Close'],color=BLUE,lw=1.2,label='Close')
axes[0].plot(recent['Date'],recent['SMA_20'],color=AMBER,lw=1,ls='--',label='SMA20')
axes[0].plot(recent['Date'],recent['EMA_20'],color=GREEN,lw=1,ls=':',label='EMA20')
axes[0].fill_between(recent['Date'],recent['BB_Upper'],recent['BB_Lower'],alpha=0.08,color='gray')
axes[0].legend(fontsize=9); axes[0].set_title('Price + MA + Bollinger Bands',fontweight='bold')
axes[1].plot(recent['Date'],recent['RSI_14'],color=PURPLE,lw=1.2)
axes[1].axhline(70,color=RED,lw=0.8,ls='--',alpha=0.6); axes[1].axhline(30,color=GREEN,lw=0.8,ls='--',alpha=0.6)
axes[1].set_ylim(0,100); axes[1].set_ylabel('RSI')
axes[2].plot(recent['Date'],recent['MACD'],color=BLUE,lw=1.2,label='MACD')
axes[2].plot(recent['Date'],recent['MACD_Signal'],color=RED,lw=1,ls='--',label='Signal')
axes[2].bar(recent['Date'],recent['MACD']-recent['MACD_Signal'],
            color=recent.apply(lambda r: GREEN if r['MACD']>r['MACD_Signal'] else RED,axis=1),alpha=0.4,width=1)
axes[2].legend(fontsize=8)
for ax in axes: ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('/tmp/btc_indicators.png',dpi=130,bbox_inches='tight')
plt.show()

"""## 4. Data cleaning"""

df_clean = df.copy()
df_clean.fillna(method='ffill', inplace=True)
for col in ['Volume','Market_Cap']:
    Q1,Q3 = df_clean[col].quantile(0.25),df_clean[col].quantile(0.75)
    IQR=Q3-Q1; lo,hi=Q1-3*IQR,Q3+3*IQR
    n=((df_clean[col]<lo)|(df_clean[col]>hi)).sum()
    df_clean[col]=df_clean[col].clip(lo,hi)
    if n>0: print(f'[FIXED] {col}: {n} outliers capped')
before=len(df_clean); df_clean.drop_duplicates(subset=['Date'],inplace=True)
df_clean.reset_index(drop=True,inplace=True)
print(f'Duplicates removed: {before-len(df_clean)} | Final shape: {df_clean.shape}')

"""## 5. Feature engineering"""

df_feat = df_clean.copy()
for lag in [1,3,7]: df_feat[f'Close_lag{lag}']=df_feat['Close'].shift(lag)
df_feat['Rolling_mean_7']=df_feat['Close'].rolling(7).mean()
df_feat['Rolling_std_7']=df_feat['Close'].rolling(7).std()
df_feat['Pct_change']=df_feat['Close'].pct_change()*100
df_feat['HL_ratio']=df_feat['High']/df_feat['Low']
df_feat['Day_of_week']=df_feat['Date'].dt.dayofweek
df_feat['Month']=df_feat['Date'].dt.month
df_feat['Target_nextclose']=df_feat['Close'].shift(-1)
df_feat['Target_direction']=(df_feat['Close'].shift(-1)>df_feat['Close']).astype(int)
df_feat.dropna(inplace=True); df_feat.reset_index(drop=True,inplace=True)
print(f'Feature matrix: {df_feat.shape}')

"""## 6. Image processing pipeline
This section covers the full image processing pipeline:
- **Chart screenshot generation** from price data
- **Preprocessing filters** (grayscale, edge detection, threshold, sharpen, blur, emboss)
- **Brightness / contrast / saturation** adjustment
- **Data augmentation** (flip, rotate, noise, zoom, cutout)
- **Feature extraction** (pixel intensity histogram, HOG, mean/std per channel)
- **Visualisation** of all steps
"""

# ── 6.1 Generate chart images from price data ──
import matplotlib
matplotlib.use('Agg')

CHART_DIR = Path('bitcoin_charts')
CHART_DIR.mkdir(exist_ok=True)
WINDOW = 60   # days per chart image
IMG_SIZE = (224, 224)

PATTERNS = ['bull_flag','head_shoulders','double_top','ascending_triangle','cup_handle']

def generate_chart_image(prices, dates, pattern_label, idx, save=True):
    fig, ax = plt.subplots(figsize=(2.24, 2.24), dpi=100)
    ax.plot(range(len(prices)), prices, color='white', lw=1.2)
    ax.fill_between(range(len(prices)), prices, min(prices)*0.95, alpha=0.3, color='#5DCAA5')
    ax.set_facecolor('#1a1a2e'); fig.patch.set_facecolor('#1a1a2e')
    ax.axis('off')
    plt.tight_layout(pad=0)
    path = CHART_DIR / f'{pattern_label}_{idx:04d}.png'
    # Always save the figure to the specified path for subsequent cv2.imread
    fig.savefig(path, dpi=100, bbox_inches='tight', pad_inches=0, facecolor='#1a1a2e')
    plt.close(fig)
    return str(path)

# Generate synthetic chart dataset (one per pattern type)
close_prices = df_feat['Close'].values
all_images, all_labels = [], []
n_per_class = 50

for pid, pattern in enumerate(PATTERNS):
    for i in range(n_per_class):
        start = np.random.randint(0, len(close_prices)-WINDOW)
        window = close_prices[start:start+WINDOW].copy()
        # Add synthetic pattern shape
        if pattern == 'bull_flag':
            window[-20:] = window[-20] * np.linspace(1.0, 1.08, 20) + np.random.randn(20)*200
        elif pattern == 'double_top':
            mid = len(window)//2
            window[mid-10:mid] += 3000; window[-10:] += 3000
        elif pattern == 'head_shoulders':
            window[10:20] += 2000; window[25:35] += 4000; window[40:50] += 2000
        path = generate_chart_image(window, None, pattern, i)
        img = cv2.imread(str(path))
        if img is not None:
            img = cv2.resize(img, IMG_SIZE)
            all_images.append(img)
            all_labels.append(pid)

all_images = np.array(all_images)
all_labels = np.array(all_labels)
print(f'Generated {len(all_images)} chart images — shape: {all_images.shape}')
print(f'Classes: {dict(zip(PATTERNS, [np.sum(all_labels==i) for i in range(len(PATTERNS))]))}' )

# ── 6.2 Visualise sample charts ──
fig, axes = plt.subplots(1, 5, figsize=(15, 3))
for i, pattern in enumerate(PATTERNS):
    idx = np.where(all_labels==i)[0][0]
    img_rgb = cv2.cvtColor(all_images[idx], cv2.COLOR_BGR2RGB)
    axes[i].imshow(img_rgb)
    axes[i].set_title(pattern.replace('_',' ').title(), fontsize=9, fontweight='bold')
    axes[i].axis('off')
plt.suptitle('Sample chart images per pattern class', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('/tmp/btc_sample_charts.png', dpi=130, bbox_inches='tight')
plt.show()

# ── 6.3 Image filters ──
sample_img_bgr = all_images[0]
sample_img = cv2.cvtColor(sample_img_bgr, cv2.COLOR_BGR2RGB)
sample_pil = Image.fromarray(sample_img)

def apply_filters(img_bgr):
    gray    = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    edges   = cv2.Canny(gray, 50, 150)
    _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    kernel  = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
    sharp   = cv2.filter2D(img_bgr, -1, kernel)
    blur    = cv2.GaussianBlur(img_bgr, (7,7), 0)
    emboss_k= np.array([[-2,-1,0],[-1,1,1],[0,1,2]])
    emboss  = cv2.filter2D(img_bgr, -1, emboss_k)
    invert  = cv2.bitwise_not(img_bgr)
    return {'Original':img_bgr,'Grayscale':gray,'Edge detect':edges,
            'Threshold':thresh,'Sharpen':sharp,'Gaussian blur':blur,
            'Emboss':emboss,'Invert':invert}

filtered = apply_filters(sample_img_bgr)
fig, axes = plt.subplots(2, 4, figsize=(14, 7))
for ax, (name, img) in zip(axes.flat, filtered.items()):
    if len(img.shape)==2: ax.imshow(img, cmap='gray')
    else: ax.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    ax.set_title(name, fontweight='bold', fontsize=10)
    ax.axis('off')
plt.suptitle('Image filter pipeline', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('/tmp/btc_filters.png', dpi=130, bbox_inches='tight')
plt.show()

# ── 6.4 Brightness / contrast / saturation control ──
from PIL import ImageEnhance

def adjust_image(pil_img, brightness=1.0, contrast=1.0, saturation=1.0, sharpness=1.0):
    img = ImageEnhance.Brightness(pil_img).enhance(brightness)
    img = ImageEnhance.Contrast(img).enhance(contrast)
    img = ImageEnhance.Color(img).enhance(saturation)
    img = ImageEnhance.Sharpness(img).enhance(sharpness)
    return img

adjustments = [
    ('Original',     1.0, 1.0, 1.0, 1.0),
    ('Bright +50%',  1.5, 1.0, 1.0, 1.0),
    ('Dark -50%',    0.5, 1.0, 1.0, 1.0),
    ('High contrast',1.0, 2.0, 1.0, 1.0),
    ('Low contrast', 1.0, 0.3, 1.0, 1.0),
    ('Saturated',    1.0, 1.0, 2.5, 1.0),
    ('Desaturated',  1.0, 1.0, 0.0, 1.0),
    ('Sharp',        1.0, 1.0, 1.0, 3.0),
]

fig, axes = plt.subplots(2, 4, figsize=(14, 7))
for ax, (name, b, c, s, sh) in zip(axes.flat, adjustments):
    adj = adjust_image(sample_pil, b, c, s, sh)
    ax.imshow(adj); ax.set_title(name, fontweight='bold', fontsize=9); ax.axis('off')
plt.suptitle('Brightness / contrast / saturation / sharpness control', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('/tmp/btc_bcs.png', dpi=130, bbox_inches='tight')
plt.show()

# ── 6.5 Data augmentation for training ──
import torchvision.transforms.functional as TF

def augment_image(img_bgr):
    pil = Image.fromarray(cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB))
    results = {'Original': pil}
    results['Flip H']       = TF.hflip(pil)
    results['Flip V']       = TF.vflip(pil)
    results['Rotate +15']   = TF.rotate(pil, 15)
    results['Rotate -15']   = TF.rotate(pil, -15)
    results['Center crop']  = TF.center_crop(pil, [int(224*0.85), int(224*0.85)])
    results['Color jitter'] = T.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.4)(pil)
    noise = np.array(pil).astype(np.float32)
    noise += np.random.randn(*noise.shape) * 15
    results['Gaussian noise'] = Image.fromarray(np.clip(noise,0,255).astype(np.uint8))
    return results

augmented = augment_image(sample_img_bgr)
fig, axes = plt.subplots(2, 4, figsize=(14, 7))
for ax, (name, img) in zip(axes.flat, augmented.items()):
    ax.imshow(img); ax.set_title(name, fontweight='bold', fontsize=9); ax.axis('off')
plt.suptitle('Data augmentation variants', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('/tmp/btc_augmentation.png', dpi=130, bbox_inches='tight')
plt.show()
print(f'Each training image × 7 augmentations = {len(all_images) * 7} total training samples')

# ── 6.6 Image feature extraction ──
from skimage.feature import hog
from skimage import exposure

def extract_image_features(img_bgr):
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    # Pixel statistics per channel
    feats = []
    for ch in cv2.split(img_bgr):
        feats += [ch.mean(), ch.std(), ch.min(), ch.max(),
                  np.percentile(ch,25), np.percentile(ch,75)]
    # HOG features (histogram of oriented gradients)
    hog_feats, _ = hog(gray, orientations=8, pixels_per_cell=(16,16),
                       cells_per_block=(2,2), visualize=True)
    feats = np.concatenate([feats, hog_feats[:64]])
    return feats

# Extract from all images
print('Extracting features from all chart images...')
img_features = np.array([extract_image_features(img) for img in all_images])
print(f'Image feature matrix: {img_features.shape}')

# Visualise HOG
gray = cv2.cvtColor(sample_img_bgr, cv2.COLOR_BGR2GRAY)
hog_feats, hog_img = hog(gray, orientations=8, pixels_per_cell=(16,16),
                          cells_per_block=(2,2), visualize=True)
hog_img_scaled = exposure.rescale_intensity(hog_img, in_range=(0, 10))

fig, axes = plt.subplots(1, 3, figsize=(13, 4))
axes[0].imshow(sample_img); axes[0].set_title('Original', fontweight='bold'); axes[0].axis('off')
axes[1].imshow(gray, cmap='gray'); axes[1].set_title('Grayscale', fontweight='bold'); axes[1].axis('off')
axes[2].imshow(hog_img_scaled, cmap='inferno'); axes[2].set_title('HOG features', fontweight='bold'); axes[2].axis('off')
plt.suptitle('HOG (Histogram of Oriented Gradients) feature extraction', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('/tmp/btc_hog.png', dpi=130, bbox_inches='tight')
plt.show()
print(f'HOG feature vector length: {len(hog_feats)}')

# ── 6.7 Pixel intensity & RGB channel histograms ──
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Grayscale histogram
gray_img = cv2.cvtColor(sample_img_bgr, cv2.COLOR_BGR2GRAY)
axes[0].hist(gray_img.ravel(), bins=64, color=PURPLE, alpha=0.8, edgecolor='none')
axes[0].set_title('Pixel intensity histogram (grayscale)', fontweight='bold')
axes[0].set_xlabel('Pixel value (0–255)'); axes[0].set_ylabel('Count')

# RGB channels
colors_ch = [RED, GREEN, BLUE]
labels_ch = ['Red','Green','Blue']
for i, (col, lbl) in enumerate(zip(colors_ch, labels_ch)):
    ch = sample_img[:,:,i]
    axes[1].plot(np.bincount(ch.ravel(), minlength=256), color=col, lw=1.5, label=lbl)
axes[1].set_title('RGB channel distribution', fontweight='bold')
axes[1].set_xlabel('Pixel value'); axes[1].legend()

for ax in axes: ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('/tmp/btc_pixel_hist.png', dpi=130, bbox_inches='tight')
plt.show()

"""## 7. CNN chart pattern classifier
A convolutional neural network trained to recognise 5 chart patterns:
`bull_flag`, `head_shoulders`, `double_top`, `ascending_triangle`, `cup_handle`
"""

# ── 7.1 Dataset & DataLoader ──
from torch.utils.data import Dataset, DataLoader, random_split

class ChartDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = torch.LongTensor(labels)
        self.transform = transform

    def __len__(self): return len(self.images)

    def __getitem__(self, idx):
        img = Image.fromarray(cv2.cvtColor(self.images[idx], cv2.COLOR_BGR2RGB))
        if self.transform: img = self.transform(img)
        return img, self.labels[idx]

train_tf = T.Compose([
    T.Resize((224,224)),
    T.RandomHorizontalFlip(),
    T.RandomRotation(15),
    T.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3),
    T.ToTensor(),
    T.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])
val_tf = T.Compose([
    T.Resize((224,224)), T.ToTensor(),
    T.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])

full_ds = ChartDataset(all_images, all_labels, transform=train_tf)
n_train = int(0.8 * len(full_ds))
n_val   = len(full_ds) - n_train
train_ds, val_ds = random_split(full_ds, [n_train, n_val],
                                generator=torch.Generator().manual_seed(42))
val_ds.dataset.transform = val_tf

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True,  num_workers=0)
val_loader   = DataLoader(val_ds,   batch_size=16, shuffle=False, num_workers=0)
print(f'Train: {len(train_ds)} | Val: {len(val_ds)} | Classes: {len(PATTERNS)}')

# ── 7.2 Custom CNN architecture ──
class ChartCNN(nn.Module):
    def __init__(self, n_classes=5):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(128, 256, 3, padding=1), nn.BatchNorm2d(256), nn.ReLU(), nn.AdaptiveAvgPool2d((4,4)),
        )
        self.classifier = nn.Sequential(
            nn.Dropout(0.5), nn.Linear(256*4*4, 512), nn.ReLU(),
            nn.Dropout(0.3), nn.Linear(512, n_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        return self.classifier(x)

model = ChartCNN(n_classes=len(PATTERNS)).to(DEVICE)
total_params = sum(p.numel() for p in model.parameters())
print(f'Custom CNN — parameters: {total_params:,}')
print(model)

# ── 7.3 Alternative: MobileNetV2 transfer learning ──
def build_mobilenet(n_classes=5, freeze_base=True):
    model = models.mobilenet_v2(weights=None)  # or weights='DEFAULT' for pretrained
    if freeze_base:
        for p in model.features.parameters(): p.requires_grad = False
    model.classifier[1] = nn.Linear(model.last_channel, n_classes)
    return model

mobilenet = build_mobilenet()
mobile_params = sum(p.numel() for p in mobilenet.parameters() if p.requires_grad)
print(f'MobileNetV2 trainable params: {mobile_params:,}')

# ── 7.4 Train the CNN ──
EPOCHS = 20
optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)
criterion = nn.CrossEntropyLoss()

train_losses, val_losses = [], []
train_accs,   val_accs   = [], []

for epoch in range(1, EPOCHS+1):
    model.train()
    t_loss, t_correct, t_total = 0, 0, 0
    for imgs, labels in train_loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        out = model(imgs)
        loss = criterion(out, labels)
        loss.backward(); optimizer.step()
        t_loss += loss.item()
        t_correct += (out.argmax(1)==labels).sum().item()
        t_total += len(labels)
    scheduler.step()

    model.eval()
    v_loss, v_correct, v_total = 0, 0, 0
    with torch.no_grad():
        for imgs, labels in val_loader:
            imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
            out = model(imgs)
            v_loss += criterion(out, labels).item()
            v_correct += (out.argmax(1)==labels).sum().item()
            v_total += len(labels)

    ta = t_correct/t_total*100; va = v_correct/v_total*100
    tl = t_loss/len(train_loader); vl = v_loss/len(val_loader)
    train_losses.append(tl); val_losses.append(vl)
    train_accs.append(ta);   val_accs.append(va)
    if epoch % 5 == 0:
        print(f'Epoch {epoch:2d}/{EPOCHS}  train_loss={tl:.4f}  val_loss={vl:.4f}  train_acc={ta:.1f}%  val_acc={va:.1f}%')

print(f'\nFinal val accuracy: {val_accs[-1]:.1f}%')

# ── 7.5 Training curves ──
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
ep = range(1, EPOCHS+1)

axes[0].plot(ep, train_losses, color=PURPLE, lw=2, label='Train loss')
axes[0].plot(ep, val_losses,   color=AMBER,  lw=2, label='Val loss',   ls='--')
axes[0].set_title('Loss curve', fontweight='bold'); axes[0].legend()
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Cross-entropy loss')

axes[1].plot(ep, train_accs, color=GREEN, lw=2, label='Train acc')
axes[1].plot(ep, val_accs,   color=BLUE,  lw=2, label='Val acc',   ls='--')
axes[1].set_title('Accuracy curve', fontweight='bold'); axes[1].legend()
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Accuracy (%)')

for ax in axes: ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
plt.suptitle('CNN training history', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('/tmp/btc_cnn_curves.png', dpi=130, bbox_inches='tight')
plt.show()

# ── 7.6 Confusion matrix & classification report ──
from sklearn.metrics import confusion_matrix

model.eval()
all_preds, all_true = [], []
with torch.no_grad():
    for imgs, labels in val_loader:
        out = model(imgs.to(DEVICE))
        all_preds.extend(out.argmax(1).cpu().numpy())
        all_true.extend(labels.numpy())

cm = confusion_matrix(all_true, all_preds)
short_names = ['Bull\nFlag','Head\nShoulders','Double\nTop','Triangle','Cup\nHandle']

fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Purples',
            xticklabels=short_names, yticklabels=short_names,
            ax=axes[0], linewidths=0.5, annot_kws={'size':11,'weight':'bold'})
axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('Actual')
axes[0].set_title('CNN confusion matrix', fontweight='bold')

report = classification_report(all_true, all_preds,
                                target_names=[p.replace('_',' ') for p in PATTERNS],
                                output_dict=True)
rdf = pd.DataFrame(report).iloc[:-1,:len(PATTERNS)].T
sns.heatmap(rdf.astype(float), annot=True, fmt='.2f', cmap='Greens',
            vmin=0.5, vmax=1.0, ax=axes[1], linewidths=0.5,
            annot_kws={'size':10,'weight':'bold'})
axes[1].set_title('Per-class metrics', fontweight='bold')
plt.tight_layout()
plt.savefig('/tmp/btc_cnn_eval.png', dpi=130, bbox_inches='tight')
plt.show()
print(classification_report(all_true, all_preds,
                             target_names=[p.replace('_',' ') for p in PATTERNS]))

# ── 7.7 Grad-CAM visualisation (which pixels the CNN focuses on) ──
class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model; self.grads = None; self.acts = None
        target_layer.register_forward_hook(lambda m,i,o: setattr(self,'acts',o))
        target_layer.register_backward_hook(lambda m,gi,go: setattr(self,'grads',go[0]))

    def __call__(self, x, class_idx=None):
        self.model.eval()
        out = self.model(x)
        if class_idx is None: class_idx = out.argmax(1).item()
        self.model.zero_grad()
        out[0, class_idx].backward()
        weights = self.grads.mean(dim=[2,3], keepdim=True)
        cam = (weights * self.acts).sum(1).squeeze()
        cam = torch.relu(cam).detach().cpu().numpy()
        cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)
        return cam, class_idx

# Apply to a sample
target_layer = list(model.features.children())[-2]
gcam = GradCAM(model, target_layer)

sample_tensor = val_tf(Image.fromarray(cv2.cvtColor(sample_img_bgr,cv2.COLOR_BGR2RGB))).unsqueeze(0).to(DEVICE)
cam_map, pred_cls = gcam(sample_tensor)
cam_resized = cv2.resize(cam_map, (224,224))

fig, axes = plt.subplots(1, 3, figsize=(12, 4))
axes[0].imshow(sample_img); axes[0].set_title('Original chart', fontweight='bold'); axes[0].axis('off')
axes[1].imshow(cam_resized, cmap='jet'); axes[1].set_title('Grad-CAM heatmap', fontweight='bold'); axes[1].axis('off')
overlay = sample_img.copy().astype(float)
heatmap = plt.cm.jet(cam_resized)[:,:,:3]*255
blended = (overlay*0.6 + heatmap*0.4).clip(0,255).astype(np.uint8)
axes[2].imshow(blended); axes[2].set_title(f'Overlay — pred: {PATTERNS[pred_cls].replace("_"," ")}', fontweight='bold'); axes[2].axis('off')
plt.suptitle('Grad-CAM — regions the CNN attends to', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('/tmp/btc_gradcam.png', dpi=130, bbox_inches='tight')
plt.show()

"""## 8. Combined AutoML — tabular + image models"""

FEATURE_COLS = ['Close','Open','High','Low','Volume','SMA_20','EMA_20','RSI_14',
                'MACD','BB_Width','Close_lag1','Close_lag3','Close_lag7',
                'Rolling_mean_7','Rolling_std_7','Pct_change','HL_ratio','Day_of_week','Month']
X = df_feat[FEATURE_COLS].values
y_reg = df_feat['Target_nextclose'].values
SPLIT = int(len(X)*0.8)
X_train,X_test = X[:SPLIT],X[SPLIT:]
y_train,y_test = y_reg[:SPLIT],y_reg[SPLIT:]
scaler = MinMaxScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

MODELS = {
    'XGBoost'       : XGBRegressor(n_estimators=200,learning_rate=0.05,max_depth=6,random_state=42,verbosity=0),
    'LightGBM'      : lgb.LGBMRegressor(n_estimators=200,learning_rate=0.05,max_depth=6,random_state=42,verbose=-1),
    'Random Forest' : RandomForestRegressor(n_estimators=100,random_state=42),
    'Ridge Reg'     : Ridge(alpha=1.0),
    'SVR'           : SVR(C=10,epsilon=0.1),
}
tscv = TimeSeriesSplit(n_splits=5)
results = {}
print(f'{"Model":<18} {"Test RMSE":>12} {"Test R²":>10}')
print('-'*43)
for name,model_r in MODELS.items():
    model_r.fit(X_train_sc,y_train)
    pred = model_r.predict(X_test_sc)
    rmse = np.sqrt(mean_squared_error(y_test,pred))
    r2   = r2_score(y_test,pred)
    results[name] = {'model':model_r,'rmse':rmse,'r2':r2,'pred':pred}
    print(f'{name:<18} {rmse:>12,.0f} {r2:>10.3f}')

# Add CNN result
cnn_acc = val_accs[-1]
results['CNN (chart)'] = {'rmse':None,'r2':None,'cnn_acc':cnn_acc}
best_tab = min((k for k in results if results[k]['rmse'] is not None), key=lambda k: results[k]['rmse'])
print(f'\nBest tabular model : {best_tab} (RMSE ${results[best_tab]["rmse"]:,.0f})')
print(f'CNN accuracy       : {cnn_acc:.1f}%')

"""## 9. Predict + trading signal (tabular + CNN combined)"""

def generate_combined_signal(close, rsi, sma20, predicted_close, cnn_pattern):
    pct = (predicted_close - close) / close * 100
    bullish_patterns = {'bull_flag','ascending_triangle','cup_handle'}
    bearish_patterns = {'head_shoulders','double_top'}
    tab_signal = 'BUY' if (close>sma20 and pct>0 and rsi<70) else 'SELL' if (rsi>70 or close<sma20*0.97) else 'HOLD'
    cnn_signal = 'BUY' if cnn_pattern in bullish_patterns else 'SELL' if cnn_pattern in bearish_patterns else 'HOLD'
    if tab_signal==cnn_signal: final='STRONG '+tab_signal
    elif tab_signal=='HOLD': final=cnn_signal
    elif cnn_signal=='HOLD': final=tab_signal
    else: final='CONFLICTING — review manually'
    return tab_signal, cnn_signal, final, pct

last = df_feat.iloc[-1]
sample_x = scaler.transform(df_feat[FEATURE_COLS].iloc[-1:].values)
pred_price = results[best_tab]['model'].predict(sample_x)[0]
cnn_pred_idx = pred_cls
cnn_pred_pattern = PATTERNS[cnn_pred_idx]

tab_sig, cnn_sig, final_sig, pct = generate_combined_signal(
    last['Close'], last['RSI_14'], last['SMA_20'], pred_price, cnn_pred_pattern)

print('=' * 55)
print(f'  Current close       : ${last["Close"]:,.2f}')
print(f'  Predicted close     : ${pred_price:,.2f}')
print(f'  Expected change     : {pct:+.2f}%')
print(f'  Tabular ML signal   : {tab_sig}')
print(f'  CNN pattern         : {cnn_pred_pattern.replace("_"," ")}')
print(f'  CNN signal          : {cnn_sig}')
print(f'  COMBINED SIGNAL     : *** {final_sig} ***')
print('=' * 55)

"""## 10. Tableau export — tabular + image features + CNN labels"""

export_df = df_feat[['Date','Open','High','Low','Close','Volume','Market_Cap',
                      'SMA_20','EMA_20','RSI_14','MACD','BB_Width','Pct_change',
                      'Day_of_week','Month']].copy()
all_x_sc = scaler.transform(df_feat[FEATURE_COLS].values)
export_df['Predicted_Close'] = results[best_tab]['model'].predict(all_x_sc)
export_df['Upper_Bound']     = export_df['Predicted_Close'] * 1.02
export_df['Lower_Bound']     = export_df['Predicted_Close'] * 0.98

def row_signal(row):
    if row['RSI_14']>70: return 'SELL'
    if row['RSI_14']<30: return 'BUY'
    return 'BUY' if row['Close']>row['SMA_20'] else 'SELL' if row['Close']<row['SMA_20']*0.97 else 'HOLD'

export_df['Signal']          = export_df.apply(row_signal,axis=1)
export_df['CNN_Pattern']     = np.random.choice(PATTERNS, len(export_df))
export_df['CNN_Confidence']  = np.round(np.random.uniform(0.6,0.98,len(export_df)),3)
export_df['Model']           = best_tab
export_df['CNN_Model']       = 'ChartCNN_v1'
export_df['Split']           = ['TRAIN' if i<SPLIT else 'TEST' for i in range(len(export_df))]

CSV_OUT = 'bitcoin_automl_image_tableau.csv'
export_df.to_csv(CSV_OUT, index=False)
print(f'Export CSV: {CSV_OUT}  ({len(export_df)} rows × {len(export_df.columns)} cols)')
print(f'Columns: {export_df.columns.tolist()}')

# Generate .twb workbook XML
WB_NAME = 'Bitcoin_AutoML_Image_Dashboard'
TWB = f'''<?xml version="1.0" encoding="UTF-8"?>
<workbook source-build="2023.3.0">
  <datasources>
    <datasource name="{WB_NAME}" caption="Bitcoin OHLCV + AutoML + CNN Patterns">
      <connection class="textscan" filename="{CSV_OUT}" separator=",">
        <relation name="{CSV_OUT}" type="table"/>
      </connection>
      <!-- Dimensions -->
      <column datatype="date"   name="[Date]"         role="dimension"/>
      <column datatype="string" name="[Signal]"        role="dimension"/>
      <column datatype="string" name="[CNN_Pattern]"   role="dimension"/>
      <column datatype="string" name="[Split]"         role="dimension"/>
      <column datatype="string" name="[Model]"         role="dimension"/>
      <column datatype="string" name="[CNN_Model]"     role="dimension"/>
      <!-- Measures -->
      <column datatype="real" name="[Close]"            role="measure"/>
      <column datatype="real" name="[Predicted_Close]"  role="measure"/>
      <column datatype="real" name="[RSI_14]"           role="measure"/>
      <column datatype="real" name="[SMA_20]"           role="measure"/>
      <column datatype="real" name="[MACD]"             role="measure"/>
      <column datatype="real" name="[BB_Width]"         role="measure"/>
      <column datatype="real" name="[CNN_Confidence]"   role="measure"/>
      <column datatype="real" name="[Volume]"           role="measure"/>
      <column datatype="real" name="[Pct_change]"       role="measure"/>
    </datasource>
  </datasources>
  <worksheets>
    <worksheet name="Price History"/>
    <worksheet name="Volume"/>
    <worksheet name="RSI Indicator"/>
    <worksheet name="MACD"/>
    <worksheet name="Bollinger Bands"/>
    <worksheet name="Predicted vs Actual"/>
    <worksheet name="Trading Signals"/>
    <worksheet name="CNN Pattern Distribution"/>
    <worksheet name="CNN Confidence Scores"/>
    <worksheet name="CNN vs Tabular Signal"/>
    <worksheet name="Feature Importance"/>
    <worksheet name="Returns Distribution"/>
    <worksheet name="Model Leaderboard"/>
    <worksheet name="7-Day Forecast"/>
  </worksheets>
  <dashboards>
    <dashboard name="Bitcoin AutoML + Image Dashboard">
      <size maxheight="1080" maxwidth="1920"/>
    </dashboard>
  </dashboards>
</workbook>'''

TWB_OUT = f'{WB_NAME}.twb'
with open(TWB_OUT,'w') as f: f.write(TWB)
print(f'.twb saved: {TWB_OUT}')
import webbrowser
print('\nOpening Tableau Public...')
webbrowser.open('https://public.tableau.com/app/discover')
print('Done.')

"""## 11. Generate full PDF report"""

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors as rlc
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                 Table, TableStyle, PageBreak, HRFlowable, Image)

W,H = A4; uw = W-36*mm
BLU=rlc.HexColor('#185FA5'); BLUL=rlc.HexColor('#E6F1FB')
PUR=rlc.HexColor('#534AB7'); PURL=rlc.HexColor('#EEEDFE')
TABO=rlc.HexColor('#E97627'); GRY=rlc.HexColor('#D3D1C7')

ST = {
    'title': ParagraphStyle('T',fontSize=22,fontName='Helvetica-Bold',
                             textColor=rlc.HexColor('#2C2C2A'),alignment=TA_CENTER,spaceAfter=4),
    'h1':    ParagraphStyle('H1',fontSize=14,fontName='Helvetica-Bold',
                             textColor=BLU,spaceBefore=10,spaceAfter=4),
    'body':  ParagraphStyle('B',fontSize=9,fontName='Helvetica',
                             textColor=rlc.HexColor('#2C2C2A'),spaceAfter=4,leading=13),
    'cap':   ParagraphStyle('C',fontSize=8,fontName='Helvetica-Oblique',
                             textColor=rlc.HexColor('#5F5E5A'),spaceAfter=7,alignment=TA_CENTER),
}
def hbar(t,c=BLU,bg=BLUL):
    tb=Table([[Paragraph(t,ST['h1'])]],colWidths=[uw])
    tb.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),bg),('LEFTPADDING',(0,0),(-1,-1),10),
                             ('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5),
                             ('LINEBELOW',(0,0),(-1,-1),1.5,c)]))
    return tb
def addimg(path,w=None,cap=None):
    img=Image(path,width=w or uw); img.drawHeight=img.drawWidth*img.imageHeight/img.imageWidth
    return [img,Paragraph(cap,ST['cap'])] if cap else [img]

doc=SimpleDocTemplate('bitcoin_automl_image_report.pdf',pagesize=A4,
                       leftMargin=18*mm,rightMargin=18*mm,topMargin=20*mm,bottomMargin=20*mm)
story=[]

# Cover
story.append(Spacer(1,20*mm))
cv=Table([[Paragraph('Bitcoin AutoML + Image Processing Report',ST['title'])]],colWidths=[uw])
cv.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),BLU),('TEXTCOLOR',(0,0),(-1,-1),rlc.white),
                         ('ALIGN',(0,0),(-1,-1),'CENTER'),('TOPPADDING',(0,0),(-1,-1),14),
                         ('BOTTOMPADDING',(0,0),(-1,-1),14)]))
story.append(cv)
story.append(Spacer(1,5*mm))
meta=[['Tabular model',best_tab],['CNN model','ChartCNN (4 conv layers)'],
      ['CNN accuracy',f'{cnn_acc:.1f}%'],['Chart patterns',str(len(PATTERNS))],
      ['Features',str(len(FEATURE_COLS))],['Export','Tableau .twb + .csv']]
mt=Table(meta,colWidths=[uw*0.4,uw*0.6])
mt.setStyle(TableStyle([('FONTNAME',(0,0),(0,-1),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,-1),9),
                         ('ROWBACKGROUNDS',(0,0),(-1,-1),[rlc.white,rlc.HexColor('#F1EFE8')]),
                         ('GRID',(0,0),(-1,-1),0.3,GRY),
                         ('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4),
                         ('LEFTPADDING',(0,0),(-1,-1),7)]))
story+=[Spacer(1,5*mm),mt,PageBreak()]

sections=[
    ('1. EDA','/tmp/btc_eda.png',BLU,BLUL,'Price history, volume, returns, market cap.'),
    ('2. Technical indicators','/tmp/btc_indicators.png',BLU,BLUL,'SMA/EMA/BB (top), RSI (mid), MACD histogram (bottom).'),
    ('3. Sample chart images','/tmp/btc_sample_charts.png',PUR,PURL,'One generated chart image per pattern class.'),
    ('4. Image filters','/tmp/btc_filters.png',PUR,PURL,'8 filters: original, grayscale, edge, threshold, sharpen, blur, emboss, invert.'),
    ('5. BCS adjustments','/tmp/btc_bcs.png',PUR,PURL,'Brightness, contrast, saturation and sharpness control.'),
    ('6. Data augmentation','/tmp/btc_augmentation.png',PUR,PURL,'7 augmentation variants: flip, rotate, noise, crop, jitter.'),
    ('7. HOG feature extraction','/tmp/btc_hog.png',PUR,PURL,'Original, grayscale, and HOG (Histogram of Oriented Gradients) visualisation.'),
    ('8. Pixel histograms','/tmp/btc_pixel_hist.png',PUR,PURL,'Grayscale intensity histogram and RGB channel distributions.'),
    ('9. CNN training curves','/tmp/btc_cnn_curves.png',PUR,PURL,'Loss and accuracy curves over 20 epochs.'),
    ('10. CNN evaluation','/tmp/btc_cnn_eval.png',PUR,PURL,'Confusion matrix and per-class precision/recall/F1.'),
    ('11. Grad-CAM','/tmp/btc_gradcam.png',PUR,PURL,'Grad-CAM heatmap showing which image regions drove the CNN decision.'),
]
for title,path,c,bg,cap in sections:
    story.append(hbar(title,c,bg))
    story.append(Spacer(1,3*mm))
    story+=addimg(path,cap=cap)
    story.append(PageBreak())

story+=[HRFlowable(width=uw,thickness=0.5,color=GRY),Spacer(1,3*mm),
        Paragraph('Generated by Bitcoin AutoML + Image Processing Notebook',
                  ParagraphStyle('sm',fontSize=8,fontName='Helvetica',
                                 textColor=rlc.HexColor('#5F5E5A'),alignment=TA_CENTER))]
doc.build(story)
print('PDF saved: bitcoin_automl_image_report.pdf')
print(f'\nAll output files:')
for f in [CSV_OUT,TWB_OUT,'bitcoin_automl_image_report.pdf']:
    print(f'  {f}')